#!/usr/bin/env node
// Assembles src/* into "Small Worlds AI.dc.html".
//
// The dc-runtime (support.js) parses that file by reading the literal DOM at
// load time: `<x-dc>` innerHTML becomes the template, and
// `script[data-dc-script]` textContent becomes the component JS. Both must
// be inline in the shipped file — the runtime does not fetch `src=`. So the
// editable source lives in src/ and this script inlines it into the
// generated artifact. Run `node build.js` after editing anything in src/.

const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const SRC = path.join(ROOT, "src");
const OUT_FILE = path.join(ROOT, "Small Worlds AI.dc.html");

// Pinned to the exact versions/hashes support.js's loadReactUmd() expects
// (REACT_SRI / REACT_DOM_SRI). Loading them here as plain <script> tags means
// window.React/window.ReactDOM already exist by the time support.js runs, so
// it never reaches out to unpkg.com at runtime.
const REACT_SRI = "sha384-DGyLxAyjq0f9SPpVevD6IgztCFlnMF6oW/XQGmfe+IsZ8TqEiDrcHkMLKI6fiB/Z";
const REACT_DOM_SRI = "sha384-gTGxhz21lVGYNMcdJOyq01Edg0jhn/c22nsx0kyqP0TxaV5WVdsSH1fSDUf5YJj1";

function escapeHtmlAttr(value) {
  return value.replace(/&/g, "&amp;").replace(/"/g, "&quot;");
}

function build() {
  const template = fs.readFileSync(path.join(SRC, "template.html"), "utf8").replace(/\s+$/, "");
  const component = fs.readFileSync(path.join(SRC, "component.js"), "utf8").replace(/\s+$/, "");
  const dataProps = JSON.parse(fs.readFileSync(path.join(SRC, "data-props.json"), "utf8"));
  const dataPropsAttr = escapeHtmlAttr(JSON.stringify(dataProps));

  const out = `<!-- GENERATED by build.js from src/ — do not edit directly. Rebuild with \`node build.js\`. -->
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="./vendor/react.production.min.js" integrity="${REACT_SRI}" crossorigin="anonymous"></script>
<script src="./vendor/react-dom.production.min.js" integrity="${REACT_DOM_SRI}" crossorigin="anonymous"></script>
<script src="./support.js"></script>
</head>
<body>
<x-dc>
${template}
</x-dc>
<script type="text/x-dc" data-dc-script data-props="${dataPropsAttr}">
${component}
</script>
</body>
</html>
`;

  fs.writeFileSync(OUT_FILE, out, "utf8");
  console.log(`Built ${path.relative(ROOT, OUT_FILE)} from src/`);
}

build();
